[package]
name = "go_parser"
version = "0.0.0"
authors = ["Charlie Somerville <charlie@charlie.bz>"]

[lib]
name = "go_parser"
path = "src/lib.rs"

[[bin]]
name = "parse-go"
path = "src/bin/parse_go.rs"

[build-dependencies]
lalrpop = "0.16"

[dependencies]
lalrpop-util = "0.16"
